FROM php:7.3-apache


# version 0.2

RUN apt-get update && apt-get install -y graphviz \
    && rm -rf /var/lib/apt/lists/*

# Install and enable mysqli extension
RUN docker-php-ext-install mysqli && docker-php-ext-enable mysqli

# Install xdebug and php extension for xdebug
RUN pecl install xdebug && docker-php-ext-enable xdebug

# Use the default development configuration
RUN mv "$PHP_INI_DIR/php.ini-development" "$PHP_INI_DIR/php.ini"

